# Generated by Django 6.0 on 2025-12-25 14:20

import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(default=users.models.generate_verification_code, max_length=6, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token'),
        ),
    ]
