# Generated by Django 5.2.8 on 2025-12-14 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='总数量')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='可借数量')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借阅日期')),
                ('due_date', models.DateTimeField(verbose_name='应还日期')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='归还日期')),
                ('status', models.CharField(choices=[('borrowed', '借阅中'), ('returned', '已归还'), ('overdue', '已逾期')], default='borrowed', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='books.book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
