# Generated by Django 6.0 on 2025-12-27 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_copies',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='overdue_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='逾期提醒已发送'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='reminder_1day_sent',
            field=models.BooleanField(default=False, verbose_name='1天提醒已发送'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='reminder_3days_sent',
            field=models.BooleanField(default=False, verbose_name='3天提醒已发送'),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.CharField(max_length=50, verbose_name='副本编号')),
                ('status', models.CharField(choices=[('available', '可借阅'), ('borrowed', '已借出'), ('reserved', '已预约'), ('maintenance', '维护中'), ('lost', '已丢失')], default='available', max_length=20, verbose_name='状态')),
                ('condition', models.CharField(blank=True, default='良好', max_length=50, verbose_name='品相')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '图书副本',
                'verbose_name_plural': '图书副本',
                'ordering': ['book', 'copy_number'],
                'unique_together': {('book', 'copy_number')},
            },
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='book_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_records', to='books.bookcopy', verbose_name='图书副本'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预约时间')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('notified', '已通知'), ('fulfilled', '已完成'), ('cancelled', '已取消'), ('expired', '已过期')], default='waiting', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'ordering': ['created_at'],
            },
        ),
    ]
